"""first commit

Revision ID: 22423a11429e
Revises: 
Create Date: 2022-12-26 16:19:01.745180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22423a11429e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
